name = "Create++"
author = "Spicy Gaming"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dd133077028408ba4f9d235b3bde3590eaf2b060a8b52e42844415aab07c4e94"

[versions]
forge = "40.1.60"
minecraft = "1.18.2"
