name = "Create++"
author = "Spicy Gaming"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9032129277f810ed13d030537a4c15894b4c668ae38b7cc94c302ac6189c1ecc"

[versions]
forge = "40.1.60"
minecraft = "1.18.2"
